version: '3'
services:
  flask:
    image: webapp-flask
    # container_name: webapp_flask_container
    build:
      context: .
      dockerfile: Dockerfile-flask
    security_opt:
      - apparmor=unconfined
    volumes:
      - "./:/app"
  nginx:
    image: webapp-nginx
    # container_name: webapp_nginx_container
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    security_opt:
      - apparmor=unconfined
    depends_on:
      - flask