version: '3'
services:
  redis-server:
    image: 'redis'
    security_opt:
      - apparmor=unconfined
  node-app:
    # restart: "no"
    # restart: always
    restart: on-failure
    build: .
    ports:
      - "4001:8081"
    security_opt:
      - apparmor=unconfined